[pytest]
# Where pytest should look for tests
testpaths =
    tests
    steps
# Test file naming convention
python_files = test_*.py

# Optional but good practice
python_classes = Test*
python_functions = test_*

# Enable pytest-bdd feature discovery
bdd_features_base_dir = features

;# Default pytest options
;addopts = -v --reruns 1 --reruns-delay 2

# Custom markers
markers =
    tc01case: Test case TC01
    tc02case: Test case TC02
    store:general store
    smoke: smoke test cases
    regression: regression test cases
    mobile: mobile automation tests
    web: web automation tests
    android: android tests
    ios: ios tests
    tc01APIDemos: Testcase for APIDemos
    tc02ADemos: Testcase for APIDemos2
    tc03ADemos: Testcase for APIDemo3
    tc04ADemos: Testcase for APIDemo4
    tc05ADemos: Testcase for APIDemo5
    tc06ADemos: Testcase for APIDemo6
    tc07ADemos: Testcase for APIDemo7
    APIDemos: All Testcase for APIDemos
